% This test file was generated by Copilot. Validate generated output before use.
classdef RockPaperScissorsTest < matlab.unittest.TestCase
    methods(Test)
        function testTie(testCase)
            p1 = "rock";
            p2 = "rock";
            expectedOutcome = "Tie";

            actualOutcome = rockPaperScissors(p1, p2);

            testCase.verifyEqual(actualOutcome, expectedOutcome);
        end

        function testPlayer1Wins(testCase)
            p1 = "paper";
            p2 = "rock";
            expectedOutcome = "Player 1 wins";

            actualOutcome = rockPaperScissors(p1, p2);

            testCase.verifyEqual(actualOutcome, expectedOutcome);
        end

        function testPlayer2Wins(testCase)
            p1 = "rock";
            p2 = "paper";
            expectedOutcome = "Player 2 wins";

            actualOutcome = rockPaperScissors(p1, p2);

            testCase.verifyEqual(actualOutcome, expectedOutcome);
        end

        function testInvalidInputPlayer1(testCase)
            p1 = "invalid";
            p2 = "rock";
            testCase.verifyError(@() rockPaperScissors(p1, p2), 'MATLAB:validators:mustBeMember');
        end

        function testInvalidInputPlayer2(testCase)
            p1 = "rock";
            p2 = "invalid";
            testCase.verifyError(@() rockPaperScissors(p1, p2), 'MATLAB:validators:mustBeMember');
        end
    end
end